# Generated by Django 4.0.4 on 2022-04-27 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=5, null=True)),
                ('gender2', models.CharField(max_length=3, null=True)),
                ('position', models.CharField(choices=[(None, '--선택--'), ('개발', '개발'), ('기획', '기획'), ('디자인', '디자인')], default='--선택--', max_length=10)),
                ('gender3', models.CharField(choices=[(None, '--선택--'), ('남자', '남자'), ('여자', '여자'), ('고자', '고자'), ('양성자', '양성자'), ('외계인', '외계인')], default='--선택--', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
