# Generated by Django 4.0.4 on 2022-04-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220427_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender2',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
