# Generated by Django 4.0.4 on 2022-04-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_profile_gender2_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
