# Generated by Django 4.0.4 on 2022-04-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_profile_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[(None, '선택'), ('개발', '개발'), ('기획', '기획'), ('디자인', '디자인')], default='선택', max_length=10),
        ),
    ]
