# Generated by Django 4.0.4 on 2022-05-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender2',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
