# Generated by Django 4.0.4 on 2022-04-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachcom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile2',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='nickname',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
